### ISSUE TITLE
module 'resources' has no attribute 'find'

### ISSUE THREAD

**Issue by enternalsaga** [s-du/ScribbleArchitect#1]
Hello, I got this error when running. How to fix this? Thank you.

`Traceback (most recent call last):
  File "H:\ScribbleArchitect\main.py", line 577, in <module>
    sys.exit(main(sys.argv))
  File "H:\ScribbleArchitect\main.py", line 563, in main
    window = PaintLCM(is_dark_theme)
  File "H:\ScribbleArchitect\main.py", line 118, in __init__
    self.example_paths = [res.find('img/examples/building_default.png'),
AttributeError: module 'resources' has no attribute 'find'`

**Comment by s-du** [comment]
Hi, there was a missing file (the '__init__.py' in the resources folder). It is now uploaded! My apologies

**Comment by helloWorldxj** [comment]
Has your issue been resolved? Can it finally run? Can you take a look at the pip list in your environment。Thank you very much
